name: Build and Publish
on:
  push:
    branches: [main]
jobs:
  build_and_publish:
    name: "Build and publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"
      - name: Set up Node 14
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14
          cache: npm
      - name: Install npm dependencies
        run: |
          npm i -g npm@8
          npm ci
      - name: Build and test packages
        run: npm run build:ci
      - name: Bundle packages
        run: npm run bundle:ci
      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          publish: npm run publish:changesets
          version: npm run version:changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
